### PR TITLE
Feature/web page

### PR DESCRIPTION
**Pull request by pauloguilhermepp**
This PR aims to add a simple web page to the Tutorial Maker project. Please feel free to review it, give feedback, and ask for improvements.

### CODE REVIEW

**Comment by LuskasHusty** [comment]
@pauloguilhermepp where can I review the resulting webpage?

**Comment by pauloguilhermepp** [comment]
Currently, you can access it here @LuskasHusty https://pauloguilhermepp.github.io/TutorialMaker/Index. After the PR, we can access it using another link (without my user).  If it makes sense to you, we can also create a specific repository for the web page and its link would start with the repository name.

**Comment by LuskasHusty** [comment]
We'll probably want to change this to another repo, I think it's supposed to be this one (https://github.com/SlicerLatinAmerica/SlicerLatinAmerica.github.io/) but @DouSam can clarify on that.
Even then, there are some issues: 
It seems that on the collaborations and diversity page, there's only info from the perspective of the brazillian team;
There are some minor html mistakes;
I don't think it follows the African team model on how the deliverables should be presented.

**Comment by DouSam** [comment]
@pauloguilhermepp a few things we need to change.
To clarify, the idea here is to copy [this page](https://sliceriml.github.io/translations.html) from the African team.
Because we already have [this page](https://github.com/SlicerLatinAmerica/SlicerLatinAmerica.github.io), which is the repository and the project page, there is no need to create a new one.

We need a page to show the tutorials like the African team did. To show the project, etc, we already have a page, just update that and make a PR in the other repository.

So, the activities now:
- Clone the repository https://github.com/SlicerLatinAmerica/SlicerLatinAmerica.github.io on our computer
- Update the page by:
- The content of this page, except the tutorials, https://pauloguilhermepp.github.io/TutorialMaker/Index  you can put in a page on the other repository with the name "Our Work"
- The content of this page https://pauloguilhermepp.github.io/TutorialMaker/TutorialMakerTool you can put in the same page "our Work" of the other repository, in a different section
- https://pauloguilhermepp.github.io/TutorialMaker/ProfessionalEvents Create a new page "Events" and also update the main page list with these events
- Verify if the list of members is updated on the website

Any doubts, you can create a new PR in the other repository, and post the questions in that.

**Pull request closed without merging**
